#' Generate igraph Graph from Causality Analysis Results 
#' 
#' @param causalityResults results generated by generateRPPAGraphs()
#' @return igraph graph object 
#' 
#' @concept zeptosensPkg
#' @export
generateCausalityIgraph <- function(causalityResults) {
    # Load SIF
    sif <- causalityResults$sif
    
    t1 <- sif[, c("PARTICIPANT_A", "INTERACTION_TYPE", "PARTICIPANT_B")]
    t2 <- t1[t1$INTERACTION_TYPE != "", ]
    g <- loadSifInIgraph(t2)
    
    # Get node colors
    formatTmp <- subset(causalityResults$format, componentProperty == "color" & componentType == 
        "node", select = c(componentLabel, rgbColor))
    # Unique because the Java causality returns duplicates sometimes
    formatTmp <- unique(formatTmp)
    
    nodeColors <- NULL
    
    for (i in 1:length(V(g))) {
        idx <- which(formatTmp[, "componentLabel"] == V(g)$name[i])
        
        if (length(idx) == 1) {
            rgbTmp <- strsplit(formatTmp[idx, "rgbColor"], " ")[[1]]
            
            # Values must be between 0 and 1
            t1 <- as.numeric(rgbTmp)/255
            hexColor <- do.call("rgb", as.list(t1))
            
            nodeColors <- c(nodeColors, hexColor)
        } else {
            nodeColors <- c(nodeColors, "#FFFFFF")
        }
    }
    
    # Get edge colors
    formatTmp <- subset(causalityResults$format, componentProperty == "color" & componentType == 
        "edge", select = c(componentLabel, rgbColor))
    formatTmp <- unique(formatTmp)
    
    edgeColors <- NULL
    edgeLty <- NULL
    
    for (i in 1:length(E(g))) {
        label <- paste(ends(g, E(g)[i])[1], E(g)[i]$edgeType, ends(g, E(g)[i])[2], sep = " ")
        idx <- which(formatTmp[, "componentLabel"] == label)
        
        if (length(idx) == 1) {
            rgbTmp <- strsplit(formatTmp[idx, "rgbColor"], " ")[[1]]
            t1 <- as.numeric(rgbTmp)/255
            hexColor <- do.call("rgb", as.list(t1))
            
            edgeColors <- c(edgeColors, hexColor)
            
            if (E(g)[i]$edgeType == "phosphorylates") {
                edgeLty <- c(edgeLty, 2)
            } else {
                edgeLty <- c(edgeLty, 1)
            }
        } else {
            edgeColors <- c(edgeColors, "#FFFFFF")
        }
    }
    
    V(g)$color <- nodeColors
    E(g)$color <- edgeColors
    E(g)$lty <- edgeLty
    
    return(g)
} 
