---
title: "Generate Causality SIF"
output:
  html_notebook: default
  html_document:
    toc: yes
  pdf_document:
    toc: yes
params:
  dataFileBase: "TS_48h_3D_JQ1_bt474"
  runHead: TRUE   
  geneCentric: TRUE
  doSiteMatch: FALSE
  datRows: 10
  outputDir: "./"
  dataDir: "./"
  platformFileOrg: "../zeptosensPkg/inst/targetScoreData/antibodyMap.txt"
  signedPcDir: "~/.paxtoolsRCache/"
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
require("knitr")
opts_chunk$set(fig.align="center", fig.width=6, fig.height=6, dpi=300)
```

## Purpose
* Plot SIFs generated by the Causality analysis

## Setup 
```{r loadLibraries, message=FALSE, warning=FALSE}
library(zeptosensPkg)
library(paxtoolsr)
library(igraph)
library(gsubfn)
library(GetoptLong)
library(R.utils)
```

## Set Parameters and Do File Processing 
```{r}
# Parameters are set at top in YAML section
dataFileBase <- params$dataFileBase #"TS_24h_3D_JQ1_bt474"
runHead <- params$runHead # TRUE
datRows <- params$datRows # 10
platformFileOrg <- params$platformFileOrg # "./zeptosensPkg/inst/targetScoreData/antibodyMap.txt"
outputDir <- params$outputDir # "./"
signedPcDir <- params$signedPcDir # "~/.paxtoolsRCache/"
geneCentric <- params$geneCentric # TRUE
doSiteMatch <- params$doSiteMatch # FALSE
dataDir <- params$dataDir # "./"

# Set up Paths and Process files
signedPcDir <- path.expand(signedPcDir)

valuesFile <- file.path(dataDir, qq("@{dataFileBase}.txt"))
#valuesFile <- qq("./@{dataFileBase}.txt")
valuesFile <- getAbsolutePath(valuesFile)

# Extract data from valuesFile
d1 <- read.table(valuesFile, sep="\t", header=TRUE, stringsAsFactors = FALSE)

if(runHead) {
  d2 <- head(d1, datRows)
} else {
  d2 <- tail(d1, datRows)
}

tmpFile <- tempfile()
write.table(d2, tmpFile, na="", quote=FALSE, col.names = TRUE, row.names=FALSE, sep="\t")
valuesFile <- tmpFile

# Fixes for platformsFile and make antibodyMap match values file
p1 <- read.table(platformFileOrg, sep="\t", header=TRUE, stringsAsFactors = FALSE, fill = TRUE)
drops <- c("Source")
p1 <- p1[, !(names(p1) %in% drops)]
colnames(p1) <- c("ID1", "ID2", "Symbols", "Sites", "Effect")
write.table(p1, "./platform.txt", na="", quote=FALSE, col.names = TRUE, row.names=FALSE, sep="\t")

# NOTE: DO NOT USE write_tsv; produces something incompatible with Java; ghost quotes """
#write_tsv(p1, "/Users/user/default/workspace/zeptosensPkg/spheroids/platform.txt", na="")
platformFile <- "./platform.txt"
# Needed for Java
platformFile <- getAbsolutePath(platformFile)

# Quick check that all IDs are in the platformsFile
stopifnot(length(which(d2$ID1 %in% p1$ID1)) == datRows)
```

## Generate SIF File
### Compatible
```{r}
graphType <- "compatible"

# Various parameters
baseFile <- paste0(dataFileBase, "_runHead_", runHead, "_datRows_", datRows, "_geneCentric_", geneCentric, "_graphType_", graphType)
outputFilePrefix <- file.path(outputDir, baseFile)
outputFilePrefix <- getAbsolutePath(outputFilePrefix)

if(!dir.exists(outputFilePrefix)) {
  dir.create(outputFilePrefix)
}

plotTitle <- paste0("Data: ", dataFileBase, " Type: ", graphType)
igraphFile <- file.path(outputFilePrefix, paste0(baseFile, "_igraph.png"))
jsonFile <- file.path(outputFilePrefix, paste0(baseFile, ".json"))

# Run Causality
compatible <- generateCausalityGraph(platformFile = platformFile, 
                              idColumn = "ID1", 
                              symbolsColumn = "Symbols",  
                              sitesColumn = "Sites",
                              effectColumn = "Effect", 
                              valuesFile = valuesFile, 
                              valueColumn = "change", 
                              valueThreshold = 0.001,
                              graphType = graphType, 
                              doSiteMatch = doSiteMatch,
                              geneCentric = geneCentric, 
                              outputFilePrefix = outputFilePrefix,
                              customNetworkDirectory=signedPcDir)

compatibleSif <- compatible$sif
#compatibleSif[, "graphType"] <- rep(graphType,  nrow(results$sif))

# Parse results
g <- parseCausalityToIgraph(compatible)

# Plot igraph
png(filename=igraphFile, width=800, height=800, res = 150)
plot(g, layout=layout.fruchterman.reingold, 
     edge.arrow.width=0.5, edge.arrow.size=0.5, edge.color=E(g)$color, edge.lty=E(g)$lty,
     vertex.color=V(g)$color, vertex.label.cex=0.75, vertex.label.color="black", vertex.label.family="Arial", vertex.label=V(g)$label)
title(plotTitle, cex.main=1)
dev.off()

# Export plot to Cytoscape
tmp <- toCytoscape(g)
writeLines(tmp, jsonFile)
```

### Conflicting (IGNORE)
```{r}
graphType <- "conflicting"

# Various parameters
baseFile <- paste0(dataFileBase, "_runHead_", runHead, "_datRows_", datRows, "_geneCentric_", geneCentric, "_graphType_", graphType)
outputFilePrefix <- file.path(outputDir, baseFile)
outputFilePrefix <- getAbsolutePath(outputFilePrefix)

if(!dir.exists(outputFilePrefix)) {
  dir.create(outputFilePrefix)
}

plotTitle <- paste0("Data: ", dataFileBase, " Type: ", graphType)
igraphFile <- file.path(outputFilePrefix, paste0(baseFile, "_igraph.png"))
jsonFile <- file.path(outputFilePrefix, paste0(baseFile, ".json"))

conflicting <- generateCausalityGraph(platformFile = platformFile, 
                              idColumn = "ID1", 
                              symbolsColumn = "Symbols",  
                              sitesColumn = "Sites",
                              effectColumn = "Effect", 
                              valuesFile = valuesFile, 
                              valueColumn = "change", 
                              valueThreshold = 0.001,
                              graphType = graphType, 
                              doSiteMatch = doSiteMatch,
                              geneCentric = geneCentric, 
                              outputFilePrefix = outputFilePrefix,
                              customNetworkDirectory=signedPcDir)

conflictingSif <- conflicting$sif
#conflictingSif[, "graphType"] <- rep(graphType,  nrow(conflicting$sif))

# Parse results
g <- parseCausalityToIgraph(compatible)

# Plot igraph
png(filename=igraphFile, width=800, height=800, res = 150)
plot(g, layout=layout.fruchterman.reingold, 
     edge.arrow.width=0.5, edge.arrow.size=0.5, edge.color=E(g)$color, edge.lty=E(g)$lty,
     vertex.color=V(g)$color, vertex.label.cex=0.75, vertex.label.color="black", vertex.label.family="Arial", vertex.label=V(g)$label)
title(plotTitle, cex.main=1)
dev.off()

# Export plot to Cytoscape
tmp <- toCytoscape(g)
writeLines(tmp, jsonFile)

```

## Overall Results
```{r}
graphType <- "overall"

# Various parameters
baseFile <- paste0(dataFileBase, "_runHead_", runHead, "_datRows_", datRows, "_geneCentric_", geneCentric, "_graphType_", graphType)
outputFilePrefix <- file.path(outputDir, baseFile)
outputFilePrefix <- getAbsolutePath(outputFilePrefix)

if(!dir.exists(outputFilePrefix)) {
  dir.create(outputFilePrefix)
}

plotTitle <- paste0("Data: ", dataFileBase, " Type: ", graphType)
igraphFile <- file.path(outputFilePrefix, paste0(baseFile, "_igraph.png"))
jsonFile <- file.path(outputFilePrefix, paste0(baseFile, ".json"))

# Make overall structure
sif <- rbind(compatible$sif, conflicting$sif)
format <- rbind(compatible$format, conflicting$format)

# Remove duplicates
overall <- list()
overall$sif <- unique(sif)
overall$format <- unique(format)

## Write overall results to file
write.table(overall$sif, paste0(outputFilePrefix, ".sif"), na="", quote=FALSE, col.names = TRUE, row.names=FALSE, sep="\t")
write.table(overall$format, paste0(outputFilePrefix, ".format"), na="", quote=FALSE, col.names = TRUE, row.names=FALSE, sep="\t")

# Parse results
g <- parseCausalityToIgraph(overall)

plotTitle <- paste0("Data: ", dataFileBase, " Type: ", graphType)

igraphFile <- file.path(outputFilePrefix, paste0(baseFile, "_igraph.png"))
jsonFile <- file.path(outputFilePrefix, paste0(baseFile, ".json"))

# Plot igraph
png(filename=igraphFile, width=800, height=800, res = 150)
plot(g, layout=layout.fruchterman.reingold, 
     edge.arrow.width=0.5, edge.arrow.size=0.5, edge.color=E(g)$color, edge.lty=E(g)$lty,
     vertex.color=V(g)$color, vertex.label.cex=0.75, vertex.label.color="black", vertex.label.family="Arial", vertex.label=V(g)$label)
title(plotTitle, cex.main=1)
dev.off()

# Export plot to Cytoscape
tmp <- toCytoscape(g)
writeLines(tmp, jsonFile)
```

