---
title: "Zeptosens"
output: 
  html_document:
    toc: true
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
require("knitr")
opts_knit$set(root.dir="..")
opts_chunk$set(fig.align="center", fig.width=6, fig.height=6, dpi=300)

```

## Purpose
* Zeptosens analysis

## Setup 
```{r loadLibraries, message=FALSE, warning=FALSE}
library(xlsx)
library(zeptosensPkg)
```

## Normalization
```{r}
colClasses <- c("character","character","numeric")
        
tpl_1 <- read.xlsx2("inst/dataInst/R022_A2058_sample_conc_EZQ.xlsx", colClasses=colClasses, stringsAsFactors=F, sheetIndex=1)
tpl_2 <- read.xlsx2("inst/dataInst/R023_Mel133_sample_conc_EZQ.xlsx", colClasses=colClasses, stringsAsFactors=F, sheetIndex=1)

dataA2058 <- readZeptosensXls("inst/dataInst/R022_A2058_RFI_Export_Table.xls")
dataMel133 <- readZeptosensXls("inst/dataInst/R023_Mel133_RFI_Export_Table.xls")

sampleNameEntries <- c("sample", "treatment", "time")

array1 <- readZeptosensExport(dataA2058, sampleNameEntries)
array2 <- readZeptosensExport(dataMel133, sampleNameEntries)

controlProbeIndex <- 65
antibodyNum <- unique(array1[, "antibody"])

results <- normalizeZeptosensData(array1, array2, tpl_1, tpl_2, controlProbeIndex, antibodyNum)

write.table(results$normArray1, file="inst/dataInst/normA2058.txt", sep="\t", quote=FALSE, row.names=FALSE, col.names=TRUE)
write.table(results$normArray2, file="inst/dataInst/normSkmel133.txt", sep="\t", quote=FALSE, row.names=FALSE, col.names=TRUE)
```

## Plot All Antibodies Per Drug
```{r}
normA2058 <- results$normArray1
normSkmel133 <- results$normArray2
    
antibodies <- unique(normA2058[, "antibody"])
excludeTreatments <- c("DMSO", "DMSO-2")
ctrlTreatment <- "DMSO"
ctrlTime <- "5min"
plotColNames <- c("A2058", "SkMel133")
plotRowNames <- c("0m", "5m", "15m", "30m", "1h", "12h", "24h", "48h")
plotColors <- c("darkblue","red")
plotDir <- "inst/tmp/"

plotZeptosensData(normA2058, normSkmel133, antibodies, excludeTreatments, ctrlTreatment, ctrlTime, plotColNames, plotRowNames, plotColors, plotDir)
```

## Plot Time Series Per Antibody (A2058)
```{r}
normA2058 <- results$normArray1
normSkmel133 <- results$normArray2
    
antibodies <- unique(normA2058[, "antibody"])
excludeTreatments <- c("DMSO", "DMSO-2")
ctrlTreatment <- "DMSO"
ctrlTime <- "5min"
plotColNames <- c("A2058")
plotRowNames <- c("0m", "5m", "15m", "30m", "1h", "12h", "24h", "48h")
plotColors <- rainbow(8)
plotDir <- "inst/tmp/a2058_ab_"
asPdf <- FALSE

plotZeptosensDataSingleAntibodyAllDrugs(normA2058, NULL, antibodies, excludeTreatments, ctrlTreatment, ctrlTime, plotColNames, plotRowNames, plotColors, plotDir, asPdf)
```


## Plot Time Series Per Antibody (SKMEL133)
```{r}
normSkmel133 <- results$normArray2
    
antibodies <- unique(normA2058[, "antibody"])
excludeTreatments <- c("DMSO", "DMSO-2")
ctrlTreatment <- "DMSO"
ctrlTime <- "5min"
plotColNames <- c("SKMEL133")
plotRowNames <- c("0m", "5m", "15m", "30m", "1h", "12h", "24h", "48h")
plotColors <- rainbow(8)
plotDir <- "inst/tmp/skmel133_ab_"
asPdf <- FALSE

plotZeptosensDataSingleAntibodyAllDrugs(normSkmel133, NULL, antibodies, excludeTreatments, ctrlTreatment, ctrlTime, plotColNames, plotRowNames, plotColors, plotDir, asPdf)
```

## Produce ChiBE Input File 
```{r}
antibodies <- unique(normSkmel133[, "antibody"])
genChibeExport(antibodies, chibeFilename="inst/tmp/abChibe.txt")
```

## Convert to Data Matrix
```{r}
times <- c("5min", "15min", "30min", "1hr", "12hr", "24hr", "48hr")
antibodies <- unique(normA2058[, "antibody"])

i <- 1
curAntibody <- antibodies[1]
curTreatment <- "901"

t1 <- normA2058[which(normA2058$time == times[i] & normA2058$treatment == curTreatment), ]
t2 <- normA2058[which(normA2058$time == times[i+1] & normA2058$treatment == curTreatment), ]
tDiff <- t1
tDiff$readout <- t2$readout - t1$readout
tDiff$time <- rep(paste0(times[i+1], "-", times[i]), length(tDiff$readout))

datMat <- convertIntermediateFormatToMatrix(normA2058, c("sample", "treatment", "time", "antibody"))
```
