---
title: "Zeptosens"
output: 
  html_document:
    toc: true
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
require("knitr")
opts_chunk$set(fig.align="center", fig.width=6, fig.height=6, dpi=300)
```

## Purpose
* Zeptosens analysis

## Setup 
```{r loadLibraries, message=FALSE, warning=FALSE}
library(xlsx)
library(zeptosensPkg)
```

##
```{r}
tpl_n <- read.table("inst/dataInst/tpl_norm.txt", header=TRUE, sep="\t", comment.char='')

a2058 <- readZeptosensExport("inst/dataInst/R022_A2058_RFI_Export_Table.xls", c("sampleName", "treatment", "time"))
skmel133 <- readZeptosensExport("inst/dataInst/R023_Mel133_RFI_Export_Table.xls", c("sampleName", "treatment", "time"))

orgCtrlIdx <- 65
nAb <- unique(a2058[, "antibody"])

ratios <- NULL
    
for(i in 1:length(nAb)) {
    ctrlIdx <- (orgCtrlIdx*i)-1
    
    t1 <- sum(a2058[c(ctrlIdx, ctrlIdx+1), "readout"])
    t2 <- sum(skmel133[c(ctrlIdx, ctrlIdx+1), "readout"])
    
    ratios <- c(ratios, t1/t2)
}

ratios <- data.frame(antibodyNames=nAb, ratios=ratios)

write.table(ratios, file="inst/dataInst/a2058_skmel133_ctrlRatios.txt", sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)

normCoef <- ratios[, "ratios"] %*% t(tpl_n[, "tpl_norm_const"])

tmpDf <- NULL

for(i in 1:nrow(normCoef)) {
    for(j in 1:ncol(normCoef)) {
        t1 <- a2058[(i-1)*ncol(normCoef)+j, "readout"] / normCoef[i,j]
        t2 <- skmel133[(i-1)*ncol(normCoef)+j, "readout"] / normCoef[i,j]
        
        tmpDf <- rbind(tmpDf, data.frame(a2058=t1, skmel133=t2))
    }
}

normA2058 <- cbind(a2058, normReadout=tmpDf[,"a2058"]) 
normSkmel133 <- cbind(skmel133, normReadout=tmpDf[,"skmel133"]) 

write.table(normA2058, file="inst/dataInst/normA2058.txt", sep="\t", quote=FALSE, row.names=FALSE, col.names=TRUE)
write.table(normSkmel133, file="inst/dataInst/normSkmel133.txt", sep="\t", quote=FALSE, row.names=FALSE, col.names=TRUE)
```

```{r}

normA2058
normSkmel133

antibodies <- unique(normA2058[, "antibody"])

excludeDrugs <- c("DMSO", "DMSO-2")
ctrlDrug <- "DMSO"
ctrlTime <- "5min"

# period <- 65
# t0 <- 57
# idx <- c(t0, c(1, 9, 17, 25, 33, 41, 49))
# nab <- 36
allDrugs <- unique(normA2058[, "treatment"])
tmpDrugs <- allDrugs[!(unique(normA2058[, "treatment"]) %in% excludeDrugs)]

curDrug <- tmpDrugs[1]



for(curDrug in tmpDrugs) {

    pdf(paste0("inst/dataInst/", curDrug, ".pdf"), width=20, height=14)
    par(mfrow=c(sqrt(length(antibodies)), sqrt(length(antibodies))))
    par(mar=c(1.5,2,1.5,1), oma=c(0,0,2,0))
    for(curAntibody in antibodies) {
        tmpAEntries <- normA2058[which(normA2058[, "antibody"] == curAntibody), ]
        tmpBEntries <- normSkmel133[which(normSkmel133[, "antibody"] == curAntibody), ]
        
        idx <- intersect(which(tmpAEntries[, "antibody"] == curAntibody), which(tmpAEntries[, "treatment"] == curDrug))
        
        t0Idx <- intersect(which(tmpAEntries[, "treatment"] == ctrlDrug), which(tmpAEntries[, "time"] == ctrlTime))
        allIdx <- c(t0Idx, idx)
        
        entriesWithCtrl <- cbind(tmpAEntries[allIdx, "normReadout"], tmpBEntries[allIdx, "readout"])
        colnames(entriesWithCtrl) <- c("A2058", "SkMel133")
        rownames(entriesWithCtrl) <- c("0m", "5m", "15m", "30m", "1h", "12h", "24h", "48h")
        tmpMat <- t(entriesWithCtrl)
        
        barplot(tmpMat, main=curAntibody, beside=TRUE, col=c("darkblue","red"), cex.main=0.7, cex.axis=0.7)
    }
    title(main=curDrug, outer=T)

    dev.off()
}
   
```
