---
title: "Generate Causality SIF"
output:
  html_notebook: default
  html_document:
    toc: yes
  pdf_document:
    toc: yes
params:
  dataFileBase: "TS_24h_3D_JQ1_bt474"
  runHead: TRUE   
  datRows: 10
  outputDir: "./"
  graphType: "compatible"
  platformFileOrg: "../zeptosensPkg/inst/targetScoreData/antibodyMap.txt"
  signedPcDir: "~/.paxtoolsRCache/"
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
require("knitr")
opts_chunk$set(fig.align="center", fig.width=6, fig.height=6, dpi=300)
```

## Purpose
* Plot SIFs generated by the Causality analysis

## Setup 
```{r loadLibraries, message=FALSE, warning=FALSE}
library(zeptosensPkg)
library(paxtoolsr)
library(igraph)
library(tidyverse)
library(gsubfn)
library(GetoptLong)
library(R.utils)
```

## Set Parameters and Do File Processing 
```{r}
geneCentric <- TRUE
doSiteMatch <- FALSE

# Parameters are set at top in YAML section
dataFileBase <- params$dataFileBase #"TS_24h_3D_JQ1_bt474"
runHead <- params$runHead # TRUE
datRows <- params$datRows # 10
platformFileOrg <- params$platformFileOrg # "./zeptosensPkg/inst/targetScoreData/antibodyMap.txt"
outputDir <- params$outputDir # "./"
graphType <- params$graphType # "compatible"
signedPcDir <- params$signedPcDir # "~/.paxtoolsRCache/"

# Set up Paths and Process files
baseFile <- paste0(dataFileBase, "_runHead_", runHead, "_datRows_", datRows, "_graphType_", graphType)
outputFilePrefix <- file.path(outputDir, baseFile)
outputFilePrefix <- getAbsolutePath(outputFilePrefix)

if(!dir.exists(outputFilePrefix)) {
  dir.create(outputFilePrefix)
}

signedPcDir <- path.expand(signedPcDir)

valuesFile <- qq("./@{dataFileBase}.txt")
valuesFile <- getAbsolutePath(valuesFile)

# Extract data from valuesFile
d1 <- read.table(valuesFile, sep="\t", header=TRUE, stringsAsFactors = FALSE)

if(runHead) {
  d2 <- head(d1, datRows)
} else {
  d2 <- tail(d1, datRows)
}

tmpFile <- tempfile()
write.table(d2, tmpFile, na="", quote=FALSE, col.names = TRUE, row.names=FALSE, sep="\t")
valuesFile <- tmpFile

# Fixes for platformsFile and make antibodyMap match values file
p1 <- read.table(platformFileOrg, sep="\t", header=TRUE, stringsAsFactors = FALSE, fill = TRUE)
drops <- c("Source")
p1 <- p1[, !(names(p1) %in% drops)]
colnames(p1) <- c("ID1", "ID2", "Symbols", "Sites", "Effect")
write.table(p1, "./platform.txt", na="", quote=FALSE, col.names = TRUE, row.names=FALSE, sep="\t")

# NOTE: DO NOT USE write_tsv; produces something incompatible with Java; ghost quotes """
#write_tsv(p1, "/Users/user/default/workspace/zeptosensPkg/spheroids/platform.txt", na="")
platformFile <- "./platform.txt"
# Needed for Java
platformFile <- getAbsolutePath(platformFile)

# Quick check that all IDs are in the platformsFile
stopifnot(length(which(d2$ID1 %in% p1$ID1)) == datRows)
```

## Generate SIF File
### Compatible
```{r}
# Run Causality
results <- generateCausalityGraph(platformFile = platformFile, 
                              idColumn = "ID1", 
                              symbolsColumn = "Symbols",  
                              sitesColumn = "Sites",
                              effectColumn = "Effect", 
                              valuesFile = valuesFile, 
                              valueColumn = "change", 
                              valueThreshold = 0.001,
                              graphType = graphType, 
                              doSiteMatch = doSiteMatch,
                              geneCentric = geneCentric, 
                              outputFilePrefix = outputFilePrefix,
                              customNetworkDirectory=signedPcDir)

compatibleSif <- results$sif
compatibleSif[, "graphType"] <- rep(graphType,  nrow(results$sif))
```

### Conflicting (IGNORE)
```{r, eval=FALSE}
graphType <- "conflicting"
outputFilePrefix <- file.path(outputDir, graphType)
outputFilePrefix <- getAbsolutePath(outputFilePrefix)
results <- generateCausalityGraph(platformFile = platformFile, 
                              idColumn = "ID1", 
                              symbolsColumn = "Symbols",  
                              sitesColumn = "Sites",
                              effectColumn = "Effect", 
                              valuesFile = valuesFile, 
                              valueColumn = "change", 
                              valueThreshold = 0.001,
                              graphType = graphType, 
                              doSiteMatch = doSiteMatch,
                              geneCentric = geneCentric, 
                              outputFilePrefix = outputFilePrefix,
                              customNetworkDirectory=signedPcDir)

conflictingSif <- results$sif
conflictingSif[, "graphType"] <- rep(graphType,  nrow(results$sif))

overallSif <- rbind(conflictingSif, compatibleSif)
```

## Parse SIF 
```{r}
# NOT USED
#graphType <- "conflicting"
# if(graphType == "conflicting") {
#     sif <- conflictingSif
# } else if(graphType == "compatible") {
#     sif <- compatibleSif
# } else {
#     stop("ERROR: Unknown graphType")
# }

sif <- results$sif

t1 <- sif[, c("PARTICIPANT_A", "INTERACTION_TYPE", "PARTICIPANT_B")]
t2 <- t1[t1$INTERACTION_TYPE != "",]
g <- loadSifInIgraph(t2)

# Shorten labels that have GBL
labels <- V(g)$name
idx <- which(grepl("GBL", labels))
labels[idx] <- strapplyc(V(g)$name[idx], "^(.*)\\.R\\..*$", simplify=TRUE)
g <- set_vertex_attr(g, "label", index = V(g), value=labels)
#g <- set_vertex_attr(g, "label", index = V(g), value=V(g)$name)

# Get node colors
formatTmp <- subset(results$format, componentProperty == "color" & componentType == "node", select = c(componentLabel, rgbColor))

nodeColors <- NULL 

for(i in 1:length(V(g))) {
    idx <- which(formatTmp[, "componentLabel"] == V(g)$name[i])
    
    if(length(idx) == 1) {
        rgbTmp <- strsplit(formatTmp[idx, "rgbColor"], " ")[[1]]
        
        # Values must be between 0 and 1
        t1 <- as.numeric(rgbTmp) / 255
        hexColor <- do.call("rgb", as.list(t1))
        
        nodeColors <- c(nodeColors, hexColor)
    } else {
        nodeColors <- c(nodeColors, "#FFFFFF")
    }
}

# Get edge colors 
# formatTmp <- subset(results$format, componentProperty == "color" & componentType == "edge", select = c(componentLabel, rgbColor))

edgeColors <- NULL 
edgeLty <- NULL

for(i in 1:length(E(g))) {
    label <- paste(ends(g, E(g)[i])[1], E(g)[i]$interactionType, ends(g, E(g)[i])[2], sep=" ")
    #idx <- which(formatTmp[, "componentLabel"] == label)
    
    #if(length(idx) == 1) {
        # rgbTmp <- strsplit(formatTmp[idx, "rgbColor"], " ")[[1]]
        # t1 <- as.numeric(rgbTmp) / 255
        # hexColor <- do.call("rgb", as.list(t1))
       
         if(grepl("expression", E(g)[i]$interactionType)) {
            edgeLty <- c(edgeLty, 2)            
        } else {
            edgeLty <- c(edgeLty, 1) 
        }
        
        if(grepl("^phosphorylates", E(g)[i]$interactionType) || grepl("^upregulates", E(g)[i]$interactionType)) {
            edgeColors <- c(edgeColors, "#00ff00")            
        } else {
            edgeColors <- c(edgeColors, "#ff0000")    
        }
    #} else {
    #    edgeColors <- c(edgeColors, "#FFFFFF")
    #}
}

V(g)$color <- nodeColors
E(g)$color <- edgeColors
E(g)$lty <- edgeLty
```

## Plot SIF
```{r}
plotTitle <- paste0("Data: ", dataFileBase, " Type: ", graphType)

igraphFile <- file.path(outputFilePrefix, paste0(baseFile, "_igraph.png"))
jsonFile <- file.path(outputFilePrefix, paste0(baseFile, ".json"))

png(filename=igraphFile, width=800, height=800, res = 150)
plot(g, layout=layout.fruchterman.reingold, 
     edge.arrow.width=0.5, edge.arrow.size=0.5, edge.color=E(g)$color, edge.lty=E(g)$lty,
     vertex.color=V(g)$color, vertex.label.cex=0.75, vertex.label.color="black", vertex.label.family="Arial", vertex.label=V(g)$label)
title(plotTitle, cex.main=1)
dev.off()

# Export plot to Cytoscape
tmp <- toCytoscape(g)
writeLines(tmp, jsonFile)
```









