---
title: "4 Cell Lines"
output: 
  html_document:
    toc: true
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
require("knitr")
opts_knit$set(root.dir="..")
opts_chunk$set(fig.align="center", fig.width=6, fig.height=6, dpi=300)
```

## Purpose
* Zeptosens analysis

## Setup 
```{r loadLibraries, message=FALSE, warning=FALSE}
library(xlsx)
library(zeptosensUtils)
library(zeptosensPkg)
```

## Normalization
```{r}
inputFile <- "inst/skmel475/R009_RFI_Export_Table_skmel118_skmel475.xlsx"
tmpDat <- readZeptosensXls(inputFile)

#availableCols <- c("sNumber"=sampleNumberIdx, 
#                   "sample"=sampleIdx,
#                   "treatment"=treatmentIdx,
#                   "dose"=doseIdx,
#                   "time"=timeIdx,
#                   "replicate"=replicateIdx,
#                   "date"=dateIdx,
#                   "notes"=notesIdx)
#tmp <- tmpData[which(grepl("Mel-475", tmpData[, "Sample.Name"], ignore.case=TRUE)),]

# Example Sample Name: S001_cell line_Melanoma_A2058 _DMSO_1hr_rep1

sampleNameEntries <- c("sNumber", "sample", "treatment", "time", "replicate", "date", NA)
dat <- readZeptosensExport(tmpDat, sampleNameEntries)


colClasses <- c("character","character","numeric")

tplDat <- read.xlsx2("inst/skmel475/R009_total_protein_level_skmel118_skmel475.xlsx", colClasses=colClasses, stringsAsFactors=F, sheetIndex=1)

# This is from the TPL file
nSamples <- 64

antibodyNum <- length(unique(dat[, "antibody"]))

mel_ttl_prot_norm <- totalProteinNormalization(dat, tplDat, nSamples, antibodyNum)

mel475 <- mel_ttl_prot_norm[which(grepl("Mel-475", mel_ttl_prot_norm[, "sample"], ignore.case=TRUE)),]

mel118 <- mel_ttl_prot_norm[which(grepl("Mel-118", mel_ttl_prot_norm[, "sample"], ignore.case=TRUE)),]

mel475_24 <- mel475[which(mel475$time == "24hr"),]
nSamples <- nrow(mel475_24[which(mel475_24$antibody == "Akt"),])

array1 <- mel475_24
normalFactor <- "DMSO"

mel475_ttl_unprtbed_norm <- unperturbedNormalization(array1, normalFactor, nSamples, antibodyNum)

# log2 transformation: 
mel475_ttl_unprtbed_norm$readout <- log2(mel475_ttl_unprtbed_norm$readout)

# Treatment 901 is the MEKi 

mel475_ttl_unprtbed_norm

repCnt <- 3 

which(mel475_ttl_unprtbed_norm$replicate == "rep1" & mel475_ttl_unprtbed_norm$treatment != "DMSO")

rep1 <- mel475_ttl_unprtbed_norm[mel475_ttl_unprtbed_norm$replicate == "rep1" & mel475_ttl_unprtbed_norm$treatment != "DMSO", "readout"]
rep2 <- mel475_ttl_unprtbed_norm[mel475_ttl_unprtbed_norm$replicate == "rep2" & mel475_ttl_unprtbed_norm$treatment != "DMSO", "readout"]
rep3 <- mel475_ttl_unprtbed_norm[mel475_ttl_unprtbed_norm$replicate == "rep3", "readout"]

y1 <- rbind(rep1, rep2, rep3)

y2 <- mel475_ttl_unprtbed_norm[mel475_ttl_unprtbed_norm$replicate == "rep3", ]
avg <- colSums(y1) / repCnt

y2$readout <- avg
y2$replicate <- rep("avg", nrow(y2))


y3 <- matrix(y2$readout, 1, antibodyNum)

rownames(y3) <- "MEKi24_Skmel475"
colnames(y3) <- unique(y2$antibody)

```

## Session Info
```{r}
sessionInfo()
```